import type { ArticleMeta, ArticleOutline } from "./article-schema";

export function buildArticlePrompt(
  outline: ArticleOutline,
  existingArticles: ArticleMeta[],
): string {
  const relatedArticles = outline.relatedArticles
    .map((article) => `- ${article.title} (/articles/${article.slug})`)
    .join("\n");
  const existingArticleList = existingArticles
    .slice(0, 30)
    .map((article) => `- ${article.title} (${article.slug})`)
    .join("\n");

  return `You are writing a Japanese Markdown draft for AI Product Build Lab.

Site purpose:
- Japanese media site for AI application development and AI product development.
- Current focus is useful editorial articles, not SaaS, login, payment, dashboard, or account features.
- Generated articles are drafts and must be reviewed by a human before publishing.

Content pillars:
1. Tool introductions and terminology explanations for development beginners.
2. AI application development methods, error cases, and solution guides.
3. AI-related news commentary.

Draft topic:
- Title: ${outline.title}
- Description: ${outline.description}
- Target reader: ${outline.targetReader}
- Angle: ${outline.angle}
- Category: ${outline.category}
- Tags: ${outline.tags.join(", ")}

Required exact frontmatter:
---
title: "${outline.title}"
description: "${outline.description}"
publishedAt: "{{TODAY}}"
updatedAt: "{{TODAY}}"
pillar: "${outline.pillar}"
status: "draft"
review_status: "needs_review"
priority: "normal"
estimated_publish_ready: false
needs_fact_check: false
category: "${outline.category}"
tags:
${outline.tags.map((tag) => `  - "${tag}"`).join("\n")}
---

Required structure:
- Start with a concise conclusion.
- Include target reader and assumptions.
- Explain terminology carefully when writing for beginners.
- Include tables, checklists, or Mermaid diagrams where useful.
- For error or solution articles, include investigation steps, command examples, solution steps, confirmation steps, and prevention.
- Include a related articles section using only the related article candidates below when relevant.
- End with a practical summary.

Editorial requirements:
- Write in clear, practical Japanese.
- Be developer-friendly and beginner-accessible.
- Use Markdown headings and code fences.
- Avoid thin filler content.
- Avoid exaggerated or promotional language.
- Do not invent statistics, benchmark numbers, official statements, external links, citations, prices, release dates, or legal/medical/financial advice.
- Do not mention that the article was generated by AI.
- Do not change routes, slugs, app code, or publishing behavior.
- Do not claim the draft is publish-ready.

Existing published articles to avoid duplicating:
${existingArticleList || "- None"}

Related article candidates:
${relatedArticles || "- None"}

Return only the complete Markdown article. Do not wrap it in a code fence.`;
}
